name: Deploy PDF to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install preswald playwright
          playwright install --with-deps

      - name: Generate PDF from Preswald script
        run: |
          preswald export --format pdf hello.py --output preswald_report.pdf

      - name: Copy PDF to index.html
        run: |
          cp preswald_report.pdf index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
